/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerKelolaTransaksi;
import Model.BuatLaporanTableModel;
import Model.LaporanKeuanganData;
import com.toedter.calendar.JDateChooser;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dilaaaaaaa
 */
public class KasirBuatLaporanKeuangan extends javax.swing.JDialog {
    private BuatLaporanTableModel buatLaporanTabel=new BuatLaporanTableModel();;
    private ControllerKelolaTransaksi dbTransaksi=new ControllerKelolaTransaksi();   
    private List<LaporanKeuanganData> laporanList;
    private LaporanKeuanganData laporan=new LaporanKeuanganData();
    private String date;
    private static final String DATE_FORMAT = "yyyy-MM-dd";
    /**
     * Creates new form BuatLaporanKeuangan
     */
    public KasirBuatLaporanKeuangan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        laporanList=new ArrayList<>();
        buatLaporanTabel.setLaporanList(laporanList);
        buatLaporanTabel.fireTableDataChanged();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        tanggalLabel = new javax.swing.JLabel();
        tanggalText = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        uangMasukLabel = new javax.swing.JLabel();
        totalUangText = new javax.swing.JTextField();
        kembaliButton = new javax.swing.JButton();
        buatButton = new javax.swing.JButton();
        cariButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OVERRIDE");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        judulLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        judulLabel.setText("Laporan Keuangan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(judulLabel)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        tanggalLabel.setText("Tanggal   :");

        tanggalText.setDateFormatString("yyyy-MM-dd");

        jTable1.setModel(buatLaporanTabel);
        jScrollPane1.setViewportView(jTable1);

        uangMasukLabel.setText("Total Uang Masuk :");

        kembaliButton.setText("Kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        buatButton.setText("Buat");
        buatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatButtonActionPerformed(evt);
            }
        });

        cariButton.setText("Cari");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(uangMasukLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(totalUangText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(kembaliButton)
                        .addGap(18, 18, 18)
                        .addComponent(buatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tanggalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanggalText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cariButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tanggalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cariButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uangMasukLabel)
                    .addComponent(totalUangText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buatButton)
                    .addComponent(kembaliButton))
                .addGap(0, 82, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        // TODO add your handling code here:   
        
        try {           
            if(tanggalText.getDate()==null){
                JOptionPane.showMessageDialog(this, "Isi dulu tanggalnya mas !");
            }
            else{
                SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT);
                date = sdf.format(tanggalText.getDate());
                laporanList=dbTransaksi.tampilTransaksi(date);
                buatLaporanTabel.setLaporanList(laporanList);
                buatLaporanTabel.fireTableDataChanged();
                totalUangText.setText(""+dbTransaksi.hitungTotalPemasukan(date));              
            }
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(KasirBuatLaporanKeuangan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cariButtonActionPerformed

    private void buatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatButtonActionPerformed
        try {
            // TODO add your handling code here:
            if(tanggalText.getDate()==null){
                JOptionPane.showMessageDialog(this, "Isi dulu tanggalnya mas !");
            }
            else{
                if(buatLaporanTabel.getRowCount()==0){
                    JOptionPane.showMessageDialog(this, "Data pembayarannya mana mas !");
                }
                else{
                    laporan.setNoPembayaran(dbTransaksi.getIdTransaksi());
                    laporan.setTanggal(date);
                    laporan.setPemasukan(Integer.parseInt(totalUangText.getText()));
                    dbTransaksi.tambahLaporanKeuangan(laporan);
                    laporanList=new ArrayList<>();
                    buatLaporanTabel.setLaporanList(laporanList);
                    buatLaporanTabel.fireTableDataChanged();
                    totalUangText.setText("");
                    JOptionPane.showMessageDialog(this, "Sukses...");
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(KasirBuatLaporanKeuangan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buatButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new KasirTampilanUtama().setVisible(true);
    }//GEN-LAST:event_kembaliButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KasirBuatLaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KasirBuatLaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KasirBuatLaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KasirBuatLaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buatButton;
    private javax.swing.JButton cariButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JLabel tanggalLabel;
    private com.toedter.calendar.JDateChooser tanggalText;
    private javax.swing.JTextField totalUangText;
    private javax.swing.JLabel uangMasukLabel;
    // End of variables declaration//GEN-END:variables


}
