/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ConnectionDB;
import Controller.ControllerKelolaPesanan;
import Controller.ControllerKelolaTransaksi;
import Model.DaftarPesananData;
import Model.DataTagihanTableModel;
import Model.TagihanData;
import Model.TransaksiPembayaranData;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

/**
 *
 * @author dilaaaaaaa
 */
public class KasirTransaksiPembayaran extends javax.swing.JDialog {
     private ControllerKelolaPesanan dbPesan = new ControllerKelolaPesanan();
     private DataTagihanTableModel bill = new DataTagihanTableModel();
     private ControllerKelolaTransaksi dbTransaksi = new ControllerKelolaTransaksi();
     private int total = 0;
     private int idPesanan, change,idTransaksi;    
     private List<TagihanData> tagihan;
    /**
     * Creates new form InputDataPembayaran
     */
    public KasirTransaksiPembayaran(java.awt.Frame parent, boolean modal) throws SQLException, ClassNotFoundException {
        super(parent, modal);
        
        List<TagihanData> tagihan = new ArrayList<>();
        bill.setTagihanList(tagihan);
        bill.fireTableDataChanged();    
        waktu();
        initComponents(); 
        idTransaksi = dbTransaksi.getIdTransaksi()+1;  
            kasirLabel.setText("Kasir : Bengek");
        noPembayaranValue.setText(String.valueOf(idTransaksi));
        buttonCetakStruk.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulPanel = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        jalanLabel = new javax.swing.JLabel();
        panelNoPembayaran = new javax.swing.JPanel();
        noPembayaranLabel = new javax.swing.JLabel();
        noPembayaranValue = new javax.swing.JLabel();
        panelKasir = new javax.swing.JPanel();
        kasirLabel = new javax.swing.JLabel();
        panelTanggal = new javax.swing.JPanel();
        tanggalLabel = new javax.swing.JLabel();
        tglValueLabel = new javax.swing.JLabel();
        panelWaktu = new javax.swing.JPanel();
        waktuLabel = new javax.swing.JLabel();
        waktuValueLabel = new javax.swing.JLabel();
        tabelPane = new javax.swing.JScrollPane();
        tabelDaftarTransaksi = new javax.swing.JTable();
        panelTotalTagihan = new javax.swing.JPanel();
        totalTagihanLabel = new javax.swing.JLabel();
        tagihanValueLabel = new javax.swing.JLabel();
        panelJumlahBayar = new javax.swing.JPanel();
        jumlahBayarLabel = new javax.swing.JLabel();
        jumlahBayarText = new javax.swing.JTextField();
        panelKembalian = new javax.swing.JPanel();
        uangKembalian = new javax.swing.JLabel();
        kembalianValueLabel = new javax.swing.JLabel();
        buttonCetakStruk = new javax.swing.JButton();
        prosesButton = new javax.swing.JButton();
        panelNoMeja = new javax.swing.JPanel();
        noMejaLabel = new javax.swing.JLabel();
        noMejaComboBox = new javax.swing.JComboBox();
        menuBar = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Override");

        judulPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        judulLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        judulLabel.setText("PT. Override");

        jalanLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jalanLabel.setText("Jalan Dr. Setiabudhi no. 193 Bandung");

        javax.swing.GroupLayout judulPanelLayout = new javax.swing.GroupLayout(judulPanel);
        judulPanel.setLayout(judulPanelLayout);
        judulPanelLayout.setHorizontalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulPanelLayout.createSequentialGroup()
                .addGroup(judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(judulPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jalanLabel))
                    .addGroup(judulPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(judulLabel)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        judulPanelLayout.setVerticalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jalanLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNoPembayaran.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        noPembayaranLabel.setBackground(new java.awt.Color(153, 153, 153));
        noPembayaranLabel.setText("No. Pembayaran :");

        javax.swing.GroupLayout panelNoPembayaranLayout = new javax.swing.GroupLayout(panelNoPembayaran);
        panelNoPembayaran.setLayout(panelNoPembayaranLayout);
        panelNoPembayaranLayout.setHorizontalGroup(
            panelNoPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noPembayaranLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noPembayaranValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNoPembayaranLayout.setVerticalGroup(
            panelNoPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNoPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(noPembayaranLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(noPembayaranValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelKasir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        kasirLabel.setText("Kasir                    :");

        javax.swing.GroupLayout panelKasirLayout = new javax.swing.GroupLayout(panelKasir);
        panelKasir.setLayout(panelKasirLayout);
        panelKasirLayout.setHorizontalGroup(
            panelKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKasirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kasirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelKasirLayout.setVerticalGroup(
            panelKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kasirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        panelTanggal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        tanggalLabel.setText("Tanggal :");

        javax.swing.GroupLayout panelTanggalLayout = new javax.swing.GroupLayout(panelTanggal);
        panelTanggal.setLayout(panelTanggalLayout);
        panelTanggalLayout.setHorizontalGroup(
            panelTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTanggalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );
        panelTanggalLayout.setVerticalGroup(
            panelTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tanggalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tglValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelWaktu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        waktuLabel.setText("Waktu :");

        javax.swing.GroupLayout panelWaktuLayout = new javax.swing.GroupLayout(panelWaktu);
        panelWaktu.setLayout(panelWaktuLayout);
        panelWaktuLayout.setHorizontalGroup(
            panelWaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWaktuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waktuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waktuValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelWaktuLayout.setVerticalGroup(
            panelWaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(waktuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(waktuValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabelDaftarTransaksi.setModel(bill);
        tabelPane.setViewportView(tabelDaftarTransaksi);

        panelTotalTagihan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        totalTagihanLabel.setText("Total tagihan : ");

        javax.swing.GroupLayout panelTotalTagihanLayout = new javax.swing.GroupLayout(panelTotalTagihan);
        panelTotalTagihan.setLayout(panelTotalTagihanLayout);
        panelTotalTagihanLayout.setHorizontalGroup(
            panelTotalTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalTagihanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalTagihanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagihanValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTotalTagihanLayout.setVerticalGroup(
            panelTotalTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(totalTagihanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(tagihanValueLabel))
        );

        panelJumlahBayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jumlahBayarLabel.setText("Jumlah Bayar :");

        javax.swing.GroupLayout panelJumlahBayarLayout = new javax.swing.GroupLayout(panelJumlahBayar);
        panelJumlahBayar.setLayout(panelJumlahBayarLayout);
        panelJumlahBayarLayout.setHorizontalGroup(
            panelJumlahBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJumlahBayarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlahBayarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jumlahBayarText, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelJumlahBayarLayout.setVerticalGroup(
            panelJumlahBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJumlahBayarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelJumlahBayarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahBayarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahBayarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelKembalian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        uangKembalian.setText("Kembalian :");

        javax.swing.GroupLayout panelKembalianLayout = new javax.swing.GroupLayout(panelKembalian);
        panelKembalian.setLayout(panelKembalianLayout);
        panelKembalianLayout.setHorizontalGroup(
            panelKembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uangKembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kembalianValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelKembalianLayout.setVerticalGroup(
            panelKembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(uangKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(kembalianValueLabel))
        );

        buttonCetakStruk.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        buttonCetakStruk.setText("<html>CETAK<br> STRUK</html>");
        buttonCetakStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakStrukActionPerformed(evt);
            }
        });

        prosesButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        prosesButton.setText("HITUNG");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        panelNoMeja.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        noMejaLabel.setText("No. Meja             :");

        noMejaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--pilih--", "1", "2", "3", "4", "5", "6", "7", "8" }));
        noMejaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noMejaComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNoMejaLayout = new javax.swing.GroupLayout(panelNoMeja);
        panelNoMeja.setLayout(panelNoMejaLayout);
        panelNoMejaLayout.setHorizontalGroup(
            panelNoMejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoMejaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noMejaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noMejaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNoMejaLayout.setVerticalGroup(
            panelNoMejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNoMejaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNoMejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noMejaLabel)
                    .addComponent(noMejaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        menuHome.setText("Menu Utama");
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
        });
        menuBar.add(menuHome);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabelPane, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelNoMeja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelNoPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelWaktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(judulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonCetakStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelJumlahBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTotalTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(prosesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(judulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNoMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(panelNoPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(panelWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(tabelPane, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(buttonCetakStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelTotalTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(prosesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private int hitungKembalian(int bayar) {
        int kembalian = bayar - total;
        
        return kembalian;               
    }
    
     private void waktu() {
             ActionListener taskPerformer = new ActionListener()
             {
                 public void actionPerformed(ActionEvent evt)
                 {
                    String nama_bulan = "";
                    String nama_hari = "";
                    String nol_hari = "";
                    String nol_jam = "";
                    String nol_menit = "";
                    String nol_detik = "";
                    Date dt = new Date();
                    int nilai_tahun = dt.getYear() + 1900;
                    int nilai_bulan = dt.getMonth() + 1;
                    int nilai_hari = dt.getDate();
                    int nilai_hari1 = dt.getDay();
                    int nilai_jam = dt.getHours();
                    int nilai_menit = dt.getMinutes();
                    int nilai_detik = dt.getSeconds();
 
                    if (nilai_hari1 == 1) {nama_hari = "Senin";}
                    else if (nilai_hari1 == 2) {nama_hari = "Selasa";}
                    else if (nilai_hari1 == 3) {nama_hari = "Rabu";}
                    else if (nilai_hari1 == 4) {nama_hari = "Kamis";}
                    else if (nilai_hari1 == 5) {nama_hari = "Jum'at";}
                    else if (nilai_hari1 == 6) {nama_hari = "Sabtu";}
                    else if (nilai_hari1 == 7) {nama_hari = "Minggu";}
 
                    if (nilai_bulan == 1) {nama_bulan = "Januari";}
                    else if (nilai_bulan == 2) {nama_bulan = "Februari";}
                    else if (nilai_bulan == 3) {nama_bulan = "Maret";}
                    else if (nilai_bulan == 4) {nama_bulan = "April";}
                    else if (nilai_bulan == 5) {nama_bulan = "Mei";}
                    else if (nilai_bulan == 6) {nama_bulan = "Juni";}
                    else if (nilai_bulan == 7) {nama_bulan = "Juli";}
                    else if (nilai_bulan == 8) {nama_bulan = "Agustus";}
                    else if (nilai_bulan == 9) {nama_bulan = "September";}
                    else if (nilai_bulan == 10) {nama_bulan = "Oktober";}
                    else if (nilai_bulan == 11) {nama_bulan = "November";}
                    else if (nilai_bulan == 12) {nama_bulan = "Desember";}
 
                    if (nilai_hari <= 9) {nol_hari = "0";}
                    if (nilai_jam <= 9) {nol_jam = "0";}
                    if (nilai_menit <= 9) {nol_menit = "0";}
                    if (nilai_detik <= 9) {nol_detik = "0";}
                    String bulan = nama_bulan;
                    String hari1 = nama_hari;
                    String hari = nol_hari + Integer.toString(nilai_hari);
                    String jam = nol_jam + Integer.toString(nilai_jam);
                    String menit = nol_menit + Integer.toString(nilai_menit);
                    String detik = nol_detik + Integer.toString(nilai_detik);
                    tglValueLabel.setText("" + hari + "  " + bulan + "  " + nilai_tahun);
                    waktuValueLabel.setText("" + jam + ":" + menit + ":" + detik);                               
                 }

             };
            new Timer(1000, taskPerformer).start();
    }
     
     
    public final void setModel() throws SQLException, ClassNotFoundException{
        String meja = noMejaComboBox.getSelectedItem().toString();
        if(meja.equals("--pilih--")){
            tagihan=new ArrayList<>();
        }
        else{
            idPesanan = dbPesan.getIdPesanan();
            tagihan = dbPesan.tampilDetailTagihan(idPesanan, Integer.parseInt(meja));
        }
        
        bill.setTagihanList(tagihan);
        bill.fireTableDataChanged();
        total = dbPesan.hitungTotalTagihan(idPesanan);
        if ( !tagihan.isEmpty() == true ) { 
            tagihanValueLabel.setText(" "+Integer.toString(total));
        }
    }
     
    private void noMejaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noMejaComboBoxActionPerformed
        try {
            setModel();    
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(KasirTransaksiPembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_noMejaComboBoxActionPerformed

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        this.dispose();
        new KasirTampilanUtama().setVisible(true);
    }//GEN-LAST:event_menuHomeMouseClicked

    private void buttonCetakStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakStrukActionPerformed
         try {             
            TransaksiPembayaranData transaksi = new TransaksiPembayaranData();
            int bayar = Integer.parseInt(jumlahBayarText.getText());
            transaksi.setIdPesanan(idPesanan);
            transaksi.setIdTransaksi(idTransaksi);
            transaksi.setTotal(total);
            transaksi.setBayar(bayar);
            transaksi.setKembalian(change);
            transaksi.setJam(waktuValueLabel.getText());
             dbTransaksi.updateStatusTransaksi(idPesanan);
             dbTransaksi.tambahTransaksiPembayaran(transaksi);
            noPembayaranValue.setText("");
            kasirLabel.setText("Kasir : ");
            tagihan=new ArrayList<>();
            bill.setTagihanList(tagihan);
            bill.fireTableDataChanged();
            tagihanValueLabel.setText("");
            jumlahBayarText.setText("");
            kembalianValueLabel.setText("");
            buttonCetakStruk.setVisible(false);
             JOptionPane.showMessageDialog(this, "Cetak struk sukses");
            
             HashMap param = new HashMap();
             param.put("id_pesanan", idPesanan);
             
             JasperPrint jasperPrint = JasperFillManager.fillReport("src/Report/StrukPembayaran.jasper", param, ConnectionDB.connectDB());
             JasperViewer.viewReport(jasperPrint, false);
         } catch (SQLException ex) {
             Logger.getLogger(KasirTransaksiPembayaran.class.getName()).log(Level.SEVERE, null, ex);
         } catch (JRException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
         }
    }//GEN-LAST:event_buttonCetakStrukActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
      
        String bayarText = jumlahBayarText.getText();
        if(bill.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Data pemesanannya mana mas !");
        }
        else{
            if( bayarText.isEmpty() ){
                JOptionPane.showMessageDialog(this, "Isi dulu uangnya mas !");
                kembalianValueLabel.setText("");
            }
            else if( !bayarText.matches("[0-9]*") ){
                JOptionPane.showMessageDialog(this, "Tau uang nggak mas !");
                kembalianValueLabel.setText("");
            }
            else{
                int bayar = Integer.parseInt(bayarText);
                if( bayar >= total ){
                    change = hitungKembalian(bayar);
                    kembalianValueLabel.setText(Integer.toString(change));
                    buttonCetakStruk.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Uang ente kurang mas !");
                    kembalianValueLabel.setText("");
                }
            }
        }
    }//GEN-LAST:event_prosesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try 
//        {
//            BeautyEyeLNFHelper.frameBorderStyle=BeautyEyeLNFHelper.FrameBorderStyle.osLookAndFeelDecorated;
//            org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
//        } 
//        catch (Exception e) 
//        {
//          e.printStackTrace();
//        }
//        //</editor-fold>


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCetakStruk;
    private javax.swing.JLabel jalanLabel;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JPanel judulPanel;
    private javax.swing.JLabel jumlahBayarLabel;
    private javax.swing.JTextField jumlahBayarText;
    private javax.swing.JLabel kasirLabel;
    private javax.swing.JLabel kembalianValueLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHome;
    private javax.swing.JComboBox noMejaComboBox;
    private javax.swing.JLabel noMejaLabel;
    private javax.swing.JLabel noPembayaranLabel;
    private javax.swing.JLabel noPembayaranValue;
    private javax.swing.JPanel panelJumlahBayar;
    private javax.swing.JPanel panelKasir;
    private javax.swing.JPanel panelKembalian;
    private javax.swing.JPanel panelNoMeja;
    private javax.swing.JPanel panelNoPembayaran;
    private javax.swing.JPanel panelTanggal;
    private javax.swing.JPanel panelTotalTagihan;
    private javax.swing.JPanel panelWaktu;
    private javax.swing.JButton prosesButton;
    private javax.swing.JTable tabelDaftarTransaksi;
    private javax.swing.JScrollPane tabelPane;
    private javax.swing.JLabel tagihanValueLabel;
    private javax.swing.JLabel tanggalLabel;
    private javax.swing.JLabel tglValueLabel;
    private javax.swing.JLabel totalTagihanLabel;
    private javax.swing.JLabel uangKembalian;
    private javax.swing.JLabel waktuLabel;
    private javax.swing.JLabel waktuValueLabel;
    // End of variables declaration//GEN-END:variables
}
