/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import Controller.ControllerKelolaPesanan;
import Model.DaftarPesananData;
import Model.DaftarPesananTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

/**
 *
 * @author asus
 */
public class KokiMenuPesanan extends javax.swing.JDialog {  
    private DaftarPesananTableModel pesananTabelModel;
    private ControllerKelolaPesanan dbPesan = new ControllerKelolaPesanan();
    /**
     * Creates new form MenuPesanan
     */

    public KokiMenuPesanan(java.awt.Frame parent,boolean modal,List<DaftarPesananData> daftar) {
        super(parent, modal);       
        pesananTabelModel = new DaftarPesananTableModel(daftar);
        pesananTabelModel.setPesananList(daftar);
        pesananTabelModel.fireTableDataChanged();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulLabel = new javax.swing.JLabel();
        noMejaComboBox = new javax.swing.JComboBox();
        tabelPesananScrollPane = new javax.swing.JScrollPane();
        tablePesanan = new javax.swing.JTable();
        separator = new javax.swing.JSeparator();
        noMejaLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Override");

        judulLabel.setFont(new java.awt.Font("Panefresco 500wt", 0, 36)); // NOI18N
        judulLabel.setText("Menu yang dipesan");

        noMejaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--pilih--", "1", "2", "3", "4", "5", "6", "7", " " }));
        noMejaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noMejaComboBoxActionPerformed(evt);
            }
        });

        tablePesanan.setModel(pesananTabelModel);
        tabelPesananScrollPane.setViewportView(tablePesanan);

        noMejaLabel.setText("No. Meja   :");

        menuHome.setText("Menu Utama");
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
        });
        menuBar.add(menuHome);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabelPesananScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(noMejaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noMejaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(judulLabel)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noMejaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noMejaLabel))
                .addGap(18, 18, 18)
                .addComponent(tabelPesananScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(437, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private final void setModel() throws SQLException, ClassNotFoundException{
        List<DaftarPesananData> pesanList;
        int id = dbPesan.getIdPesanan();
        int status = dbPesan.getStatusPesanan(id);
        String meja = noMejaComboBox.getSelectedItem().toString();
        if(meja.equals("--pilih--")){
            pesanList=new ArrayList<>();
        }
        else{
           pesanList=dbPesan.tampilDaftarPesananDapur(Integer.parseInt(meja));
        }
        pesananTabelModel.setPesananList(pesanList);
        pesananTabelModel.fireTableDataChanged();
    }
    
    private void noMejaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noMejaComboBoxActionPerformed
        // TODO add your handling code here:
        try {
            setModel();    
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(KokiMenuPesanan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_noMejaComboBoxActionPerformed

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new KokiTampilanUtama().setVisible(true);
    }//GEN-LAST:event_menuHomeMouseClicked
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KokiMenuPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KokiMenuPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KokiMenuPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KokiMenuPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        try 
//        {
//            BeautyEyeLNFHelper.frameBorderStyle=BeautyEyeLNFHelper.FrameBorderStyle.osLookAndFeelDecorated;
//            org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
//        } 
//        catch (Exception e) 
//        {
//          e.printStackTrace();
//        }
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                KokiMenuPesanan dialog = new KokiMenuPesanan(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel judulLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHome;
    private javax.swing.JComboBox noMejaComboBox;
    private javax.swing.JLabel noMejaLabel;
    private javax.swing.JSeparator separator;
    private javax.swing.JScrollPane tabelPesananScrollPane;
    private javax.swing.JTable tablePesanan;
    // End of variables declaration//GEN-END:variables
}
