/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.ControllerKelolaMenu;
import Model.DaftarMenuData;
import java.awt.event.ItemEvent;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

/**
 *
 * @author asus
 */
public class KokiStatusMenu extends javax.swing.JDialog {
    private DaftarMenuData menu;
    private List<DaftarMenuData> listMenu = new ArrayList<>();
    private ControllerKelolaMenu db = new ControllerKelolaMenu();
    
    /**
     * Creates new form StatusMenuDesert
     */
    public KokiStatusMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusButtonGroup = new javax.swing.ButtonGroup();
        namaMenuLabel = new javax.swing.JLabel();
        namaMenuComboBox = new javax.swing.JComboBox();
        tersediaRadioButton = new javax.swing.JRadioButton();
        habisRadioButton = new javax.swing.JRadioButton();
        ubahButton = new javax.swing.JButton();
        kembaliButton = new javax.swing.JButton();
        panelLabel = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        daftarMenuLabel = new javax.swing.JLabel();
        kategoriComboBox = new javax.swing.JComboBox();
        menuBar = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        namaMenuLabel.setText("Nama menu             :");

        namaMenuComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMenuComboBoxActionPerformed(evt);
            }
        });

        statusButtonGroup.add(tersediaRadioButton);
        tersediaRadioButton.setText("Tersedia");
        tersediaRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tersediaRadioButtonItemStateChanged(evt);
            }
        });

        statusButtonGroup.add(habisRadioButton);
        habisRadioButton.setText("Habis");
        habisRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                habisRadioButtonItemStateChanged(evt);
            }
        });

        ubahButton.setFont(new java.awt.Font("Panefresco 250wt", 1, 18)); // NOI18N
        ubahButton.setText("Ubah");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        kembaliButton.setFont(new java.awt.Font("Panefresco 250wt", 1, 18)); // NOI18N
        kembaliButton.setText("Kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        panelLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));

        judulLabel.setFont(new java.awt.Font("Panefresco 250wt", 1, 24)); // NOI18N
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("Ubah Status");

        javax.swing.GroupLayout panelLabelLayout = new javax.swing.GroupLayout(panelLabel);
        panelLabel.setLayout(panelLabelLayout);
        panelLabelLayout.setHorizontalGroup(
            panelLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLabelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(judulLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLabelLayout.setVerticalGroup(
            panelLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judulLabel)
                .addContainerGap())
        );

        statusLabel.setText("Status                      :");

        daftarMenuLabel.setText("Kategori                  :");

        kategoriComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- pilih kategori ---", "Makanan", "Minuman", "Dessert" }));
        kategoriComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriComboBoxActionPerformed(evt);
            }
        });

        menuHome.setText("Menu Utama");
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
        });
        menuBar.add(menuHome);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaMenuLabel)
                            .addComponent(statusLabel)
                            .addComponent(daftarMenuLabel))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kategoriComboBox, 0, 152, Short.MAX_VALUE)
                            .addComponent(namaMenuComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(kembaliButton)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tersediaRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(habisRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(ubahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daftarMenuLabel)
                    .addComponent(kategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaMenuLabel)
                    .addComponent(namaMenuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(tersediaRadioButton)
                    .addComponent(habisRadioButton))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubahButton)
                    .addComponent(kembaliButton))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(429, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        String nama = namaMenuComboBox.getSelectedItem().toString();
        db.ubahStatusMenu(menu.getStatus(),nama);
        
    }//GEN-LAST:event_ubahButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new KokiTampilanUtama().setVisible(true);
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new KokiTampilanUtama().setVisible(true);
    }//GEN-LAST:event_menuHomeMouseClicked
    
    // ------------------ get Radio Button Value ----------------------------
     private void itemStateChange(ItemEvent e) {
        Object source = e.getItemSelectable();
        menu=new DaftarMenuData();
        
        if ( source == tersediaRadioButton ) {
            menu.setStatus("tersedia");
        }
        else if ( source == habisRadioButton ) {
            menu.setStatus("habis");
        }  
    }
     
    // -------------------- set Combo Box model -----------------------------------
    private final void setModel() throws SQLException, ClassNotFoundException{
        String kategori = kategoriComboBox.getSelectedItem().toString();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        listMenu = db.tampilDaftarMenu(kategori);
        
        for (DaftarMenuData menus : listMenu) {
            model.addElement(menus.getNama());
        }
        namaMenuComboBox.setModel(model);
        status();
    }
    
    private void kategoriComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriComboBoxActionPerformed
        try {
            setModel();    
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(KokiStatusMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_kategoriComboBoxActionPerformed

    private void tersediaRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tersediaRadioButtonItemStateChanged
        itemStateChange(evt);
    }//GEN-LAST:event_tersediaRadioButtonItemStateChanged

    private void habisRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_habisRadioButtonItemStateChanged
        itemStateChange(evt);
    }//GEN-LAST:event_habisRadioButtonItemStateChanged

    private void namaMenuComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMenuComboBoxActionPerformed
        status();
    }//GEN-LAST:event_namaMenuComboBoxActionPerformed
    
    // -------- get status menu dari database --------------------------
    public void status() {
        String kategori = kategoriComboBox.getSelectedItem().toString();
        String nama = namaMenuComboBox.getSelectedItem().toString();        
        try {
            String status = db.tampilDaftarMenu(nama, kategori); // tampilkan status menu yang terpilih
            switch (status) {
                case "tersedia":
                    tersediaRadioButton.doClick();
                    break;
                case "habis":
                    habisRadioButton.doClick();
                    break;
            }
          
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(KokiStatusMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftarMenuLabel;
    private javax.swing.JRadioButton habisRadioButton;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JComboBox kategoriComboBox;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHome;
    private javax.swing.JComboBox namaMenuComboBox;
    private javax.swing.JLabel namaMenuLabel;
    private javax.swing.JPanel panelLabel;
    private javax.swing.ButtonGroup statusButtonGroup;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JRadioButton tersediaRadioButton;
    private javax.swing.JButton ubahButton;
    // End of variables declaration//GEN-END:variables
}
