/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerKelolaMenu;
import Model.DaftarMenuData;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

/**
 *
 * @author Syauqi Rahmat Sugara
 */
public class ManajerUbahMenu extends javax.swing.JDialog {
    ControllerKelolaMenu db = new ControllerKelolaMenu();
    /**
     * Creates new form TambahMenu
     */
    public ManajerUbahMenu(java.awt.Dialog parent, boolean modal)throws SQLException,ClassNotFoundException{
        super(parent, modal);
        initComponents();
        kodeMenuText.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ubahMenuPanel = new javax.swing.JPanel();
        ubahMenu = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();
        namaMenuText = new javax.swing.JTextField();
        hargaMenuText = new javax.swing.JTextField();
        kembaliButton = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();
        kodeLabel = new javax.swing.JLabel();
        kodeMenuText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Override");

        ubahMenuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        ubahMenu.setFont(new java.awt.Font("Panefresco 250wt", 0, 28)); // NOI18N
        ubahMenu.setText("Ubah Menu ");

        namaLabel.setText("Nama             :");

        hargaLabel.setText("Harga            :");

        kembaliButton.setText("Kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        ubahButton.setText("Ubah");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        kodeLabel.setText("Kode              :");

        javax.swing.GroupLayout ubahMenuPanelLayout = new javax.swing.GroupLayout(ubahMenuPanel);
        ubahMenuPanel.setLayout(ubahMenuPanelLayout);
        ubahMenuPanelLayout.setHorizontalGroup(
            ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubahMenuPanelLayout.createSequentialGroup()
                .addGroup(ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ubahMenuPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ubahMenuPanelLayout.createSequentialGroup()
                                .addComponent(kembaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ubahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namaLabel)
                                .addGroup(ubahMenuPanelLayout.createSequentialGroup()
                                    .addGroup(ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hargaLabel)
                                        .addComponent(kodeLabel))
                                    .addGap(24, 24, 24)
                                    .addGroup(ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(namaMenuText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hargaMenuText, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addComponent(kodeMenuText, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(ubahMenuPanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(ubahMenu)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        ubahMenuPanelLayout.setVerticalGroup(
            ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubahMenuPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ubahMenu)
                .addGap(41, 41, 41)
                .addGroup(ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeMenuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodeLabel))
                .addGap(30, 30, 30)
                .addGroup(ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaMenuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hargaMenuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(ubahMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubahButton)
                    .addComponent(kembaliButton))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ubahMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ubahMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(447, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        
        DaftarMenuData dm=new DaftarMenuData();
        String kode = kodeMenuText.getText();
        String nama = namaMenuText.getText();
        String harga = hargaMenuText.getText();
         
        try {            
            if ( !kode.isEmpty() && !nama.isEmpty() && !harga.isEmpty()) {
                if(harga.matches("[0-9]*")){
                    dm.setKode(kode);
                    dm.setNama(nama);
                    dm.setHarga(Integer.parseInt(harga)); 
                    db.ubahDaftarMenu(dm.getKode(), dm.getHarga(), dm.getNama());
                    ManajerKelolaMenu kelolaMenu = new ManajerKelolaMenu(this, true);
                    this.dispose();
                    kelolaMenu.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Harga harus format angka");
                }
            }
            else {
                    JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
            }
                
        } catch (SQLException ex) {
            Logger.getLogger(ManajerUbahMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManajerUbahMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
                  
    }//GEN-LAST:event_ubahButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        ManajerKelolaMenu kelolaMenu;
        try {
            kelolaMenu = new ManajerKelolaMenu(this, true);
            this.dispose();
            kelolaMenu.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManajerUbahMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_kembaliButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hargaLabel;
    public javax.swing.JTextField hargaMenuText;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JLabel kodeLabel;
    public javax.swing.JTextField kodeMenuText;
    private javax.swing.JLabel namaLabel;
    public javax.swing.JTextField namaMenuText;
    private javax.swing.JButton ubahButton;
    private javax.swing.JLabel ubahMenu;
    private javax.swing.JPanel ubahMenuPanel;
    // End of variables declaration//GEN-END:variables
}
