/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerKelolaPesanan;
import Model.DaftarPesananData;
import Model.TagihanData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;

/**
 *
 * @author dilaaaaaaa
 */
public class PelangganTampilanUtama extends javax.swing.JFrame {
    private List<DaftarPesananData> pesanan;
    private List<TagihanData> tagihan;
    private ControllerKelolaPesanan dbPesan = new ControllerKelolaPesanan();
    
     
    /**
     * Creates new form PelangganTampilanUtama
     */
    public PelangganTampilanUtama() {
        initComponents();
    }
    
     public PelangganTampilanUtama(List<DaftarPesananData> daftar1, List<TagihanData> daftar2) {
        this.pesanan = daftar1;
        this.tagihan = daftar2;
        initComponents();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuPanel = new javax.swing.JPanel();
        buttonMenu = new javax.swing.JButton();
        buttonOrder = new javax.swing.JButton();
        buttonTagihan = new javax.swing.JButton();
        judulPanel = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setLayout(new java.awt.GridLayout(1, 3));

        buttonMenu.setFont(new java.awt.Font("Panefresco 250wt", 0, 18)); // NOI18N
        buttonMenu.setText("<html>Daftar<br> Menu</html>");
        buttonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuActionPerformed(evt);
            }
        });
        menuPanel.add(buttonMenu);

        buttonOrder.setFont(new java.awt.Font("Panefresco 250wt", 0, 18)); // NOI18N
        buttonOrder.setText("<html><center>Daftar</center> Order</html>");
        buttonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrderActionPerformed(evt);
            }
        });
        menuPanel.add(buttonOrder);

        buttonTagihan.setFont(new java.awt.Font("Panefresco 250wt", 0, 18)); // NOI18N
        buttonTagihan.setText("<html><center>Lihat</center>Tagihan</html>");
        buttonTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTagihanActionPerformed(evt);
            }
        });
        menuPanel.add(buttonTagihan);

        judulPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        judulPanel.setLayout(new java.awt.GridBagLayout());

        judulLabel.setFont(new java.awt.Font("Drift Wood", 0, 48)); // NOI18N
        judulLabel.setText("WELCOME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 33, 26, 36);
        judulPanel.add(judulLabel, gridBagConstraints);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(judulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(judulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuActionPerformed
        PelangganDaftarMenu daftarMenu;
       
        try {
            daftarMenu = new PelangganDaftarMenu(this, true);
            this.dispose();
            daftarMenu.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PelangganTampilanUtama.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PelangganTampilanUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
            

    }//GEN-LAST:event_buttonMenuActionPerformed

    private void buttonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrderActionPerformed
        PelangganDaftarPesanan daftarOrder;
        try {
                int id = dbPesan.getIdPesanan();
                int status = dbPesan.getStatusPesanan(id);
                if ( status == 1 ) {
                    pesanan = new ArrayList<>();
                    daftarOrder = new PelangganDaftarPesanan(this, true, pesanan);
                    this.dispose();
                    daftarOrder.setVisible(true);
                }
                else {
                    pesanan = dbPesan.tampilDaftarPesananPelanggan();
                    daftarOrder = new PelangganDaftarPesanan(this, true, pesanan);
                    this.dispose();
                    daftarOrder.setVisible(true);
                }                
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(PelangganTampilanUtama.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_buttonOrderActionPerformed

    private void buttonTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTagihanActionPerformed
        PelangganTagihan daftarTagihan;
            try {
                int id = dbPesan.getIdPesanan();
                int status = dbPesan.getStatusPesanan(id);
                if ( status == 1 ) {
                    tagihan = new ArrayList<>();
                    daftarTagihan = new PelangganTagihan(this, true,tagihan, 1);
                    this.dispose();
                    daftarTagihan.setVisible(true);
                }
                else {
                    tagihan = dbPesan.tampilTagihan(id);
                    daftarTagihan = new PelangganTagihan(this, true,tagihan, id);
                    this.dispose();
                    daftarTagihan.setVisible(true);
                }                
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(PelangganTampilanUtama.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_buttonTagihanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try 
        {
            BeautyEyeLNFHelper.frameBorderStyle=BeautyEyeLNFHelper.FrameBorderStyle.osLookAndFeelDecorated;
            org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
        } 
        catch (Exception e) 
        {
          e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PelangganTampilanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMenu;
    private javax.swing.JButton buttonOrder;
    private javax.swing.JButton buttonTagihan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JPanel judulPanel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
