/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerKelolaPesanan;
import Model.DaftarPesananData;
import Model.DaftarPesananTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Syauqi Rahmat Sugara
 */
public class PelayanDaftarPesanan extends javax.swing.JDialog {
    private DaftarPesananTableModel pesananTabelModel;
    private ControllerKelolaPesanan dbPesan = new ControllerKelolaPesanan();
    
    /**
     * Creates new form DaftarOrder1
     */
    public PelayanDaftarPesanan(java.awt.Frame parent, boolean modal, List<DaftarPesananData> daftar) {
        super(parent, modal);
        
        pesananTabelModel = new DaftarPesananTableModel(daftar);
        pesananTabelModel.setPesananList(daftar);
        pesananTabelModel.fireTableDataChanged();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesananPanel = new javax.swing.JPanel();
        judulPanel = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        pesananPane = new javax.swing.JScrollPane();
        tabelDaftarPesanan = new javax.swing.JTable();
        noMejaComboBox = new javax.swing.JComboBox();
        noMejaLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pesananPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        judulPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        judulLabel.setFont(new java.awt.Font("Panefresco 250wt", 0, 24)); // NOI18N
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("Menu yang dipesan");

        javax.swing.GroupLayout judulPanelLayout = new javax.swing.GroupLayout(judulPanel);
        judulPanel.setLayout(judulPanelLayout);
        judulPanelLayout.setHorizontalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        judulPanelLayout.setVerticalGroup(
            judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tabelDaftarPesanan.setModel(pesananTabelModel);
        pesananPane.setViewportView(tabelDaftarPesanan);

        noMejaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--pilih--", "1", "2", "3", "4", "5", "6", "7", " " }));
        noMejaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noMejaComboBoxActionPerformed(evt);
            }
        });

        noMejaLabel.setText("No. Meja   :");

        javax.swing.GroupLayout pesananPanelLayout = new javax.swing.GroupLayout(pesananPanel);
        pesananPanel.setLayout(pesananPanelLayout);
        pesananPanelLayout.setHorizontalGroup(
            pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesananPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pesananPanelLayout.createSequentialGroup()
                        .addComponent(noMejaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noMejaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pesananPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(judulPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pesananPanelLayout.setVerticalGroup(
            pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesananPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(judulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noMejaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noMejaLabel))
                .addGap(18, 18, 18)
                .addComponent(pesananPane, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        menuHome.setText("Menu Utama");
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
        });
        menuBar.add(menuHome);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesananPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesananPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(416, 451));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        try {
            new PelayanTampilanUtama().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PelayanDaftarPesanan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PelayanDaftarPesanan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuHomeMouseClicked
    
    
    private final void setModel() throws SQLException, ClassNotFoundException{
        List<DaftarPesananData> pesanList;
        int id = dbPesan.getIdPesanan();
        int status = dbPesan.getStatusPesanan(id);
        String meja =(noMejaComboBox.getSelectedItem().toString());
        if(meja.equals("--pilih--")){
            pesanList=new ArrayList<>();
        }
        else{
            pesanList=dbPesan.tampilDaftarPesananDapur( Integer.parseInt(meja));
        }
        
        pesananTabelModel.setPesananList(pesanList);
        pesananTabelModel.fireTableDataChanged();
    }
    
    
    private void noMejaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noMejaComboBoxActionPerformed
        // TODO add your handling code here:
        try {
            setModel();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PelayanDaftarPesanan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_noMejaComboBoxActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel judulLabel;
    private javax.swing.JPanel judulPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHome;
    private javax.swing.JComboBox noMejaComboBox;
    private javax.swing.JLabel noMejaLabel;
    private javax.swing.JScrollPane pesananPane;
    private javax.swing.JPanel pesananPanel;
    private javax.swing.JTable tabelDaftarPesanan;
    // End of variables declaration//GEN-END:variables
}
